[Chaos] - Add ansible to also provision chaos when installing
skodjob/automation-hub pull request #338
Opened 2024-02-08 14:52 UTC by see-quick

2024-02-08 14:54 UTC, Frawless requested changes
You should create new task file for chaos I think. Adding it to infra doesn't sounds right. Maybe put it to strimzi instead?

2024-02-08 14:55 UTC, see-quick commented
> You should create new task file for chaos I think. Adding it to infra doesn't sounds right. Maybe put it to strimzi instead?

I was also thinking about it. So I think it would be best to choose own chaos file then

2024-02-08 15:11 UTC, Frawless commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('file', item) }}"
I think this will fail because you are going to apply j2 template before processing it

2024-02-08 15:19 UTC, see-quick commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('file', item) }}"
Yeah...tomorrow I will take a look at that :)

2024-02-12 12:11 UTC, kornys requested changes

2024-02-12 12:11 UTC, kornys commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +  tags:
remove tags from there...

2024-02-12 12:11 UTC, kornys commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +  tags:
remove tags from there

2024-02-12 12:11 UTC, kornys commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('template', item) }}"
do not use definition if you using templates

2024-02-12 13:00 UTC, see-quick commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('template', item) }}"
So should I change it to use resource_definition i.e., also change fileglob to loop and query...?
```yaml
- name: Deploy chaos engineering resources for Tekton from Jinja2 templates
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    resource_definition: "{{ lookup('template', item) }}"
    verify_ssl: no
    apply: true
  loop: "{{ query('fileglob', 'templates/tekton/pipelines/chaos/*.j2') }}"
  ```

2024-02-12 15:00 UTC, kornys commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('template', item) }}"
see other examples, instead of resource_definition use template

2024-02-12 15:31 UTC, Frawless commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('template', item) }}"
I think it is fine to use `definition` in that case, however, we use `template` even if we don't process it with Jinja because in case we add some variable it is not straightforward to find the issue. An example with fileglob is here https://github.com/skodjob/automation-hub/blob/main/install/roles/automation-hub/tasks/scenario-deployment/tekton/infra-tkn-pipelines.yaml#L28

2024-02-12 16:11 UTC, see-quick commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('template', item) }}"
> I think it is fine to use definition in that case, however, we use template even if we don't process it with Jinja because in case we add some variable 

Thanks for the explanation I was wondering why you use a template even if you don't process it with Jinja. I will update it accordingly :)

2024-02-12 16:26 UTC, see-quick commented on install/roles/automation-hub/tasks/scenario-deployment/tekton/chaos-tkn-pipelines.yaml
> +    definition: "{{ lookup('template', item) }}"
updated @Frawless @kornys

2024-02-12 17:13 UTC, kornys approved these changes

2024-02-12 17:47 UTC, see-quick commented
> Guess in the future it would make sense to use some variables for config the cluster names, etc. Have some chaos config part. But definitely not in this PR.

For sure that's a good idea.

2024-02-12 17:50 UTC, merged